# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import tweetme.tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweetme.tweets.validators.validate_content]),
        ),
    ]
