# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import tweetme.tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweetme.tweets.models.validate_content]),
        ),
    ]
