dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install -q -r requirements.txt
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - coverage run --source='tweetme' manage.py test
before_install:
  - pip install coveralls
after_success:
  - coveralls
