language: python
python:
  - "3.6.0"
install:
  - pip install -q -r requirements.txt
services:
  - postgresql
before_script:
  - sudo -u postgres createuser test
  - psql -c 'create database test_db;' -U postgres
  - python manage.py migrate
script:
  - coverage run --source='tweetme' manage.py test
before_install:
  - pip install coveralls
after_success:
  - coveralls