language: python
python:
  - "3.6.0"
dist: trusty
sudo: required
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -q -r requirements.txt
before_script:
  - psql -c 'create database tweetme;' -U tweetmeadmin
  - python manage.py migrate
script:
  - coverage run --source='tweetme' manage.py test
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - pip install coveralls
after_success:
  - coveralls