language: python
python:
  - "3.6.0"
addons:
  postgresql: "9.5"
services:
  - postgresql
dist: trusty
sudo: required
install:
  - pip install -q -r requirements.txt
before_script:
  - psql -c 'create database tweetme;' -U tweetmeadmin
  - python manage.py migrate
script:
  - coverage run --source='tweetme' manage.py test
before_install:
  - pip install coveralls
after_success:
  - coveralls